In [2]:
# Q1: You are given the following arrays:
import numpy as np
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])

c = (a*b)
print(c)
# Task: Multiply 'a' and 'b' using broadcasting.
# What is the resulting array?


[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [5]:
# Q2: Given an array of integers:
arr = np.array([5, 2, 7, 1, 9, 3])


mask = arr <= 5 
c = arr[mask]=-1
print(arr)

# Task: Replace all elements less than 5 with -1.
# Expected output: array([-1, -1, 7, -1, 9, -1])


[-1 -1  7 -1  9 -1]


In [12]:
# Q3: You have a 1D array of 12 elements:
arr = np.arange(12)

c = arr.reshape(3, 4)
print(c)

d = c.sum(axis=0)
print(d)
# Task:
#   - Reshape it into a 3x4 matrix.
#   - Then find the sum along columns (axis=0).


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]


In [22]:
# Q4: You are given two 1D arrays:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


c = np.vstack((a,b))
print(c)


# Horizontal stacking (requires reshaping to (3,1) for both arrays)
h = np.hstack((a.reshape(-1, 1), b.reshape(-1, 1)))
print(h)
# Task:
# Stack them into a 2D array of shape (2, 3) using:
# - Vertical stacking
# - Horizontal stacking (requires reshaping)


[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
