In [5]:
# 1d array
import numpy as np
a= np.array([1,2,3], dtype="int8")
print(a)

[1 2 3]


In [ ]:
# 3d-dimension
b=np.array([[[1,2,3],[2,3,5],[2,3,5]]])
print(b)

In [ ]:
# get dimensions
a.ndim

In [ ]:
# shape of the array rows , columns of dimensions..
# a.shape
b.shape

In [ ]:
# data type it takes int64 as default
a.dtype
b.dtype

In [ ]:
# get size of the bytes from itemsize
a.itemsize
b.itemsize

# accessing / changing the elements, rows ,columns etc..

In [17]:
a = np.array([[[1,2,3,4,5,6,7],[12,34,56,657,34,34,54],[3,4,5,67,7,5,6]]])
print(a)

[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [18]:
# get a specific element like [r,c] and all starts from index 0
element = a[0, 1, 3]
print(element)
print(a)


657
[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [19]:
# getting a specific row and column
selected=a[0,1,:]
print(selected)

sel = a[0,:,5]
print(sel)


[ 12  34  56 657  34  34  54]
[ 6 34  5]


In [20]:
# changing elements 
a[0,0,0] = 2
print(a)


[[[  2   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [21]:
# changing elements of a whole 

a[0,:,6]=2
print(a)


a[0,:,6]=[2,3,4]
print(a)

[[[  2   2   3   4   5   6   2]
  [ 12  34  56 657  34  34   2]
  [  3   4   5  67   7   5   2]]]
[[[  2   2   3   4   5   6   2]
  [ 12  34  56 657  34  34   3]
  [  3   4   5  67   7   5   4]]]


# intializing different types of array


In [25]:
# zero matrix 

# a =np.zeros((2,3))
a = np.zeros(((1,3,3)))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [26]:
# ones matrix 

a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#  any other number like two parameter np.full(shape,value)and full_like for (a , value)
a =np.full((2,4),56)
print(a)

[[56 56 56 56]
 [56 56 56 56]]


In [ ]:
# random decimal value in the matrix 
a = np.random.rand(4,3)
print(a)

[[0.47598572 0.37577065 0.13380212]
 [0.20368677 0.96793961 0.84306072]
 [0.45866654 0.98956604 0.43447183]
 [0.02374314 0.64446198 0.71527616]]


In [32]:
# random integer value 
a = np.random.randint(3,5,(3,4))
print(a)

[[4 3 4 4]
 [3 3 4 3]
 [4 3 4 3]]


In [33]:
# indentity matrix 
a = np.identity(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [38]:
# repeat an array 
a = np.array([[1,3,5]])
r1 = np.repeat(a,4,0)
print(r1)

[[1 3 5]
 [1 3 5]
 [1 3 5]
 [1 3 5]]


In [43]:
#assignemt -1
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
z[1,1]=9
print(z)

a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## careful during copying the arrays !

In [ ]:
# a = np.array([2,3,5])
# print(a)
# b=a
# print(b)
# b[0]=34
# print(b)
# print(a) #here is the issue where anything done on b does reflect on a as well thats not copy is...
# to avoid the above thing you can just do the .copy()

a = np.array([2,3,5])
b= a.copy()
b[0]=34
print(b)
print(a) # here you can check that the result has not affected on a due to change in b..

[34  3  5]
[2 3 5]


# mathematics


In [ ]:
# arithmetic operation in np
a = np.array([1,2,3,4])

a+=2
print(a)

a-=2
print(a)

a*=2
print(a)

a=a/2
print(a)



[3 4 5 6]
[1 2 3 4]
[2 4 6 8]
[1. 2. 3. 4.]


In [10]:
# operation as the array

c = np.array([1,2,3,4])
print(a+c)


a =a**2
print(a)

[2. 4. 6. 8.]
[ 1.  4.  9. 16.]


In [11]:
# trignometric function

a = np.cos(a)
print(a)


[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]


In [2]:
import numpy as np
b = np.array([[1, 2], [3, 4], [5, 6]])
reshaped = b.reshape(2, 3)
print(reshaped)


[[1 2 3]
 [4 5 6]]


In [6]:
# numpy broadcasting ...
b = np.array([[1, 2], [3, 4], [5, 6]])

# adding a scalar
a = (1+b)
print(a)

#Adding row to 2D matrix

c = np.array([[1,2,3],[4,5,6]])
d = np.array([10,10,10])
print(c+d)

a = np.ones((3, 1))  # shape (3, 1)
b = np.array([1, 2, 3])  # shape (3,)
result = a * b  # what’s the result shape?
print(result)


[[2 3]
 [4 5]
 [6 7]]
[[11 12 13]
 [14 15 16]]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [9]:
# stacking array

a = np.array([1, 2])
b = np.array([3, 4])
c =  np.vstack((a, b))
d = np.hstack((a,b))
e = np.stack((a,b))
print(c)
print(d)
print(e)



[[1 2]
 [3 4]]
[1 2 3 4]
[[1 2]
 [3 4]]


In [12]:
# some indexing tricks 

# boolean indexing..

a = np.array([10, 20, 30, 40, 50])
mask = a > 25
print(a[mask])  

# fancy indexing

a = np.array([10, 20, 30, 40, 50])
idx = [1, 3, 4]
print(a[idx]) 


# where() indexing

a = np.array([1, 2, 3, 4, 5])
b = np.where(a % 2 == 0, "Even", "Odd")
print(b)


[30 40 50]
[20 40 50]
['Odd' 'Even' 'Odd' 'Even' 'Odd']


In [ ]:
# basics tasks 

# Broadcast a 1D array over a 2D array

a = np.array([[1,3,5],[6,3,2]])
b = np.array([10,20,30])
print(a+b)

# Stack arrays to form a 3D array

a = np.ones((2, 2))
b = np.zeros((2, 2))
c = np.stack((a,b), axis=0)
print(c)

# boolean condition for  all elements > 4

arr = np.array([[1, 5, 3], [6, 2, 8]])
mask = arr > 4 
print(arr[mask])


[[11 23 35]
 [16 23 32]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]
[5 6 8]
