In [1]:
# 1d array
import numpy as np
a= np.array([1,2,3], dtype="int8")
print(a)

[1 2 3]


In [ ]:
# 3d-dimension
b=np.array([[[1,2,3],[2,3,5],[2,3,5]]])
print(b)

In [ ]:
# get dimensions
a.ndim

In [ ]:
# shape of the array rows , columns of dimensions..
# a.shape
b.shape

In [ ]:
# data type it takes int64 as default
a.dtype
b.dtype

In [ ]:
# get size of the bytes from itemsize
a.itemsize
b.itemsize

# accessing / changing the elements, rows ,columns etc..

In [17]:
a = np.array([[[1,2,3,4,5,6,7],[12,34,56,657,34,34,54],[3,4,5,67,7,5,6]]])
print(a)

[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [18]:
# get a specific element like [r,c] and all starts from index 0
element = a[0, 1, 3]
print(element)
print(a)


657
[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [19]:
# getting a specific row and column
selected=a[0,1,:]
print(selected)

sel = a[0,:,5]
print(sel)


[ 12  34  56 657  34  34  54]
[ 6 34  5]


In [20]:
# changing elements 
a[0,0,0] = 2
print(a)


[[[  2   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [21]:
# changing elements of a whole 

a[0,:,6]=2
print(a)


a[0,:,6]=[2,3,4]
print(a)

[[[  2   2   3   4   5   6   2]
  [ 12  34  56 657  34  34   2]
  [  3   4   5  67   7   5   2]]]
[[[  2   2   3   4   5   6   2]
  [ 12  34  56 657  34  34   3]
  [  3   4   5  67   7   5   4]]]


# intializing different types of array


In [25]:
# zero matrix 

# a =np.zeros((2,3))
a = np.zeros(((1,3,3)))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [26]:
# ones matrix 

a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#  any other number like two parameter np.full(shape,value)and full_like for (a , value)
a =np.full((2,4),56)
print(a)

[[56 56 56 56]
 [56 56 56 56]]


In [ ]:
# random decimal value in the matrix 
a = np.random.rand(4,3)
print(a)

[[0.47598572 0.37577065 0.13380212]
 [0.20368677 0.96793961 0.84306072]
 [0.45866654 0.98956604 0.43447183]
 [0.02374314 0.64446198 0.71527616]]


In [32]:
# random integer value 
a = np.random.randint(3,5,(3,4))
print(a)

[[4 3 4 4]
 [3 3 4 3]
 [4 3 4 3]]


In [33]:
# indentity matrix 
a = np.identity(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [38]:
# repeat an array 
a = np.array([[1,3,5]])
r1 = np.repeat(a,4,0)
print(r1)

[[1 3 5]
 [1 3 5]
 [1 3 5]
 [1 3 5]]


In [43]:
#assignemt -1
a = np.ones((5,5))
print(a)

z = np.zeros((3,3))
z[1,1]=9
print(z)

a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## careful during copying the arrays !

In [ ]:
# a = np.array([2,3,5])
# print(a)
# b=a
# print(b)
# b[0]=34
# print(b)
# print(a) #here is the issue where anything done on b does reflect on a as well thats not copy is...
# to avoid the above thing you can just do the .copy()

a = np.array([2,3,5])
b= a.copy()
b[0]=34
print(b)
print(a) # here you can check that the result has not affected on a due to change in b..

[34  3  5]
[2 3 5]


# mathematics


In [ ]:
a = np.array([1,2,3,4])

a+=2
print(a)

a-=2
print(a)



[3 4 5 6]
[1 2 3 4]
