In [25]:
# 1d array
import numpy as np
a= np.array([1,2,3], dtype="int8")
print(a)

[1 2 3]


In [13]:
# 3d-dimension
b=np.array([[[1,2,3],[2,3,5],[2,3,5]]])
print(b)

[[[1 2 3]
  [2 3 5]
  [2 3 5]]]


In [17]:
# get dimensions
a.ndim

1

In [ ]:
# shape of the array rows , columns of dimensions..
# a.shape
b.shape

(1, 3, 3)

In [ ]:
# data type it takes int64 as default
a.dtype
b.dtype

dtype('int64')

In [ ]:
# get size of the bytes from itemsize
a.itemsize
b.itemsize

1

# accessing / changing the elements, rows ,columns etc..

In [34]:
a = np.array([[[1,2,3,4,5,6,7],[12,34,56,657,34,34,54],[3,4,5,67,7,5,6]]])
print(a)

[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [38]:
# get a specific element like [r,c] and all starts from index 0
element = a[0, 1, 3]
print(element)
print(a)


657
[[[  1   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]


In [43]:
# getting a specific row and column
selected=a[0,1,:]
print(selected)

sel = a[0,:,5]
print(sel)


[ 12  34  56 657  34  34  54]
[ 6 34  5]


In [44]:
# changing elements 
a[0,0,0] = 2
print(a)


[[[  2   2   3   4   5   6   7]
  [ 12  34  56 657  34  34  54]
  [  3   4   5  67   7   5   6]]]
