# linear algebra

In [4]:
import numpy as np
a = np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

# a*b

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinant
c = np.identity(3)
r = np.linalg.det(c)
print(r)

1.0
