# basics of statistics 

In [ ]:
# ptp()-----> peak to peak -----> max to min range

# axis basically tells where the operation is performe like :
# if axis is 0 then its done max-min in column wise
# if axis is 1 then its done max-min in row wise 
# if you have negative input in array then you will get result as mathematically
# to view result as unsigned you can use the view(dtype)

import numpy as np

x = np.array([[1,3,4],[10,4,5]])
print(x)
col =np.ptp(x, axis=0)
row =np.ptp(x, axis=1)
whole = np.ptp(x)

print(whole)

[[ 1  3  4]
 [10  4  5]]
9


In [ ]:
# percentile()
# x percentile gives y means that out of all values in dataset x percentage of values are less than y and values are just median.

a = np.array([[1,5,3],[6,7,8]])

perc = np.percentile(a,50)
percc = np.percentile(a,50,axis=0)
percr = np.percentile(a,50,axis=1)
print(perc)
print(percc)
print(percr)


5.5
[3.5 6.  5.5]
[3. 7.]


In [18]:
# median()

# if the # of values are odd its middle element
# if the # of values are even its two mean of two middle element


b = np.array([[1,4,3],[2,3,4],[2,8,5]])
print(b)
median = np.median(b)
medianc = np.median(b,axis=0)
medianr = np.median(b,axis=1)
print(median)
print(medianc)
print(medianr)

[[1 4 3]
 [2 3 4]
 [2 8 5]]
3.0
[2. 4. 4.]
[3. 3. 5.]


In [22]:
# average

c = np.arange(1,8)
print(c)
print(np.average(c))



[1 2 3 4 5 6 7]
4.0
